# Generated by Django 5.2.5 on 2025-09-02 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_todolist_task_due_date_alter_task_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_date']},
        ),
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['-created_at']},
        ),
    ]
